// Author: Lucas Berg
// =============================================================================================
// Program that reads a Purkinje network generated by the Fractal Tree algorithm (.xyz and .ien) 
// and converted to a .vtk
// 
//
// Pre-Requisites:
//  - GCC/G++ 
//  - CMake
//  - Valgrind (for memory leak check ...)
//
//  Features of this program:
//
//
//
// How to compile:
//  $ ./recompile_project.sh
// =============================================================================================

#include <cstdio>
#include <cstdlib>

#include "vtk_polydata/vtk_polydata.h"

int main (int argc, char *argv[])
{
    if (argc-1 < 3)
    {
        usage(argv[0]);
        exit(EXIT_FAILURE);
    }

    char *xyz_filename = argv[1];
    char *ien_filename = argv[2];
    char *vtk_filename = argv[3];

    VTK_Polydata *polydata = new VTK_Polydata(xyz_filename,ien_filename);

    polydata->write_to_vtk(vtk_filename);

    return 0;
}
